# Generated by Django 4.1.1 on 2022-10-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_converter_get_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converter',
            name='get_amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Мы получаем'),
        ),
    ]
